<?php

namespace AppBundle\Repository;

/**
 * ChildFoodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChildFoodRepository extends \Doctrine\ORM\EntityRepository
{
}
