<?php

namespace AppBundle\Repository;

/**
 * ChildFoodTagRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChildFoodTagRepository extends \Doctrine\ORM\EntityRepository
{
}
