<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * ChildRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChildRepository extends \Doctrine\ORM\EntityRepository
{
    public function getChild(User $user){
        return $this->createQueryBuilder('i')
            ->select('i')
            ->andWhere('i.user = :userid')
            ->setParameter('userid', $user)
            ->getQuery()
            ->getResult();
    }
}
