<?php

namespace AppBundle\Repository;

/**
 * FoodTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoodTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
