<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Season;
use Doctrine\ORM\QueryBuilder;

/**
 * menuRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListMenus()
    {
        $qb = $this->createQueryBuilder('m')
            ->select('m')
            ->orderBy('m.name')
            ->getQuery()
            ->getResult();

        return $qb;
    }

    public function getMenuById($id)
    {
        $q = $this->createQueryBuilder('m')
            ->andWhere('m.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();
        return $q;
    }

    public function getRandomMenus($limit = 5, Season $season = null){

        $qb = $this->createQueryBuilder('m')
            ->addSelect('RAND() as HIDDEN rand')
            ->addOrderBy('rand');

        if(null !== $season){
            $qb->leftJoin('m.season','s')
                ->where('s.id = :idSeason')
                ->setParameter(':idSeason', $season->getId());
        }

        $qb->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }



    public function getSearchMenu($search)
    {
        $qb =  $this->createQueryBuilder('m')
            ->select('m')
            ->where('m.name LIKE :searchWord')
            ->setParameter(':searchWord', '%'.$search->getKeyword().'%');

        if(null !== $search->getAge()){
            $qb
                ->innerJoin('m.recipes', 'r', 'WITH', 'r.age <= :age')
                ->addSelect('r')
                ->setParameter(':age', $search->getAge());
        }

        return $qb
            ->getQuery()
            ->getResult();

    }

}
