<?php

namespace AppBundle\Repository;

/**
 * menuRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class menuRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListMenu()
    {
        $qb = $this->createQueryBuilder('m')
            ->select('m')
            ->orderBy('m.name')
            ->getQuery()
            ->getResult();

        return $qb;
    }

    public function getMenuById($id)
    {
        $q = $this->createQueryBuilder('m')
            ->andWhere('m.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();
        return $q;
    }



}
