<?php

namespace AppBundle\Repository;
/**
 * menuRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListMenus()
    {
        $qb = $this->createQueryBuilder('m')
            ->select('m')
            ->orderBy('m.name')
            ->getQuery()
            ->getResult();

        return $qb;
    }

    public function getMenuById($id)
    {
        $q = $this->createQueryBuilder('m')
            ->andWhere('m.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();
        return $q;
    }

    public function getRandomMenus($limit = 5, $idSeason){

        return $this->createQueryBuilder('m')
            ->addSelect('RAND() as HIDDEN rand')
            ->addOrderBy('rand')
            ->leftJoin('m.season','s')
            ->where('s.id = :idSeason')
            ->setParameter(':idSeason', $idSeason)
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }



}
