<?php

namespace AppBundle\Repository;

/**
 * MessageContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageContactRepository extends \Doctrine\ORM\EntityRepository
{
}
