<?php

namespace AppBundle\Repository;

/**
 * PhotoRecipeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRecipeRepository extends \Doctrine\ORM\EntityRepository
{

}
