<?php

namespace AppBundle\Repository;

/**
 * RecipeTypeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
