<?php

namespace AppBundle\Repository;


/**
 * seasonRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSeasonByDate($dateT)
    {
        return $this->createQueryBuilder('s')
            ->select('s')
            ->where(':dateT BETWEEN s.dateBegin AND s.dateEnd')
            ->setParameter('dateT', $dateT)
            ->getQuery()
            ->getOneOrNullResult();

    }
}
