<?php

namespace AppBundle\Repository;

/**
 * seasonRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class seasonRepository extends \Doctrine\ORM\EntityRepository
{
}
