app:
    resource: '@AppBundle/Controller/'
    type: annotation

# FosUser routing
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


# Sonata Admin routing
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin



