# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
   app.child.manager:
       class: AppBundle\Manager\ChildManager
       arguments:
              - "@=service('doctrine').getManager()"

   app.childfood.manager:
          class: AppBundle\Manager\ChildFoodManager
          arguments:
                 - "@=service('doctrine').getManager()"

imports:
    - { resource: '@AppBundle/Resources/config/services.yml' }
    - { resource: '@AppBundle/Resources/config/admin_services.yml' }