# src/AppBundle/Resources/config/services.yml
services:
    app.user_registation:
        class: AppBundle\EventListener\UserRegistrationListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }