# src/AppBundle/Resources/config/services.yml
services:
    app.user_registation:
        class: AppBundle\EventListener\UserRegistrationListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }

    app.menu_manager:
        class: AppBundle\Manager\MenuManager
        arguments:
            - "@=service('doctrine').getManager()"

    app.doctrine.listener.photo_recipe:
        class: AppBundle\Doctrine\Listener\PhotoRecipeListener
        arguments:
            - "%photo_recipe_directory%"
        tags:
            - { name: doctrine.event_listener, event: preRemove, connetion: default}